variable "vpc_id" {}
variable "subnet_id" {}
variable "tag-prod-alb" {}
variable "certificate_arn" {}
variable "security_group_ids" {}
variable "tag-stage-alb" {}
variable "worker_node1" {}
variable "worker_node2" {}
variable "worker_node3" {}